W10D1/music_app_specs_exercise/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

  root to: "bands#index"
end

W10D1/music_app_specs_exercise/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  live?      :boolean          default(FALSE), not null
#  band_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :year, presence: true
  validates :live?, inclusion: [true, false]

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

W10D1/music_app_specs_exercise/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login

  def new
    @album = Album.new
    @album.band_id = params[:band_id]
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:success] = "New album added!"
      redirect_to band_url(@album.band_id)
    else
      flash.now[:error] = @album.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    if @album
      render :edit
    else
      flash[:error] = "Sorry, album not found."
      redirect_to bands_url
    end
  end

  def show
    @album = Album.find_by(id: params[:id])
    @band = Band.find_by(id: @album.band_id)
    if @album
      render :show
    else
      flash[:error] = "Sorry, album not found."
      redirect_to bands_url
    end
  end

  def update
    @album = Album.find_by(id: params[:id])

    if @album.update(album_params)
      flash[:success] = "Album successfully edited!"
      redirect_to album_url(@album.id)
    else
      flash.now[:error] = @album.errors.full_messages
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    if @album
      flash[:success] = "Album successfully removed!"
      @album.destroy
      redirect_to band_url(@album.band_id)
    else
      flash[:error] = "Sorry, that album was not found."
      redirect_to bands_url, status: 404
    end
  end

  private

  def album_params
    params.require(:album).permit(:title, :year, :live?, :band_id)
  end
end

W10D1/music_app_specs_exercise/app/views/albums/_form.html.erb
<% if album.persisted? %>
  <% action_url = album_url(album.id) %>
  <% button_text = "Update album" %>
  <% hidden_method = "PATCH" %>
<% else %>
  <% action_url = albums_url %>
  <% button_text = "Add album!" %>
  <% hidden_method = "POST" %>
<% end %>

<head>
  <style>

    form {
      display: flex;
      flex-direction: column;
      align-items: flex-start;
      line-height: 3;
    }

    input[type=radio] {
      margin: 0px 5px;
    }

    button {
      margin: 5px 0px;
    }
    
  </style>
</head>

<form action="<%= action_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= hidden_method %>">

  <label for="title">Title:
    <input type="text" name="album[title]" value="<%= album.title %>" id="title">
  </label>

  <label for="band">Band:
    <select name="album[band_id]" id="band">
      <% Band.all.each do |band| %>
        <option <%= "selected" if album.band_id == band.id %> value="<%= band.id %>">
          <%= band.name %>
        </option>
      <% end %>
    </select>
  </label>

  <label for="year">Year:
    <input type="text" name="album[year]" value="<%= album.year %>" id="year">
  </label>

  <label>
    Recording setting:
    <input
      <%= "checked" unless album.live? || album.live?.nil? %>
      type="radio" 
      name="album[live?]" 
      value="false"
      id="studio"
    />
    <label for="studio">Studio</label>
    <input
      <%= "checked" if album.live?  %>
      type="radio" 
      name="album[live?]" 
      value="true"
      id="live"
      />
    <label for="live">Live</label>
  </label>

  <button><%= button_text %></button>
</form>

W10D1/music_app_specs_exercise/app/views/albums/edit.html.erb
<h1>Edit album</h1>
<%= render partial: 'form', locals: { album: @album } %>

W10D1/music_app_specs_exercise/app/views/albums/new.html.erb
<h1>Add a new album!</h1>
<%= render partial: 'form', locals: { album: @album } %>

W10D1/music_app_specs_exercise/app/views/albums/show.html.erb
<h1>Album: <%= @album.title %></h1>
<h3>Band: <%= @band.name %></h3>
<h3>Year: <%= @album.year %></h3>
<h3>Recorded <%= @album.live? ? "live" : "in the studio" %></h3>
<h3>Tracks:</h3>
<ol>
  <% @album.tracks.each do |track| %>
  <li><%= link_to "#{track.title}", track_url(track.id) %></li>
  <% end %>
</ol>

<%= button_to "Add a track!", new_album_track_url(@album.id), method: :get %>
<%= button_to "Edit album", edit_album_url(@album.id), method: :get %>
<%= button_to "Remove album", album_url(@album.id), method: :delete %>
<%= button_to "Back to band: #{@band.name}", band_url(@band.id), method: :get %>