W10D1/music_app_specs_exercise/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

  root to: "bands#index"
end

W10D1/music_app_specs_exercise/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint           not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums
end

W10D1/music_app_specs_exercise/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login

  def index
    @bands = Band.all
    render :index
  end

  def create
    @band = Band.create(band_params)

    if @band.save
      flash[:success] = "New band added!"
      redirect_to band_url(@band.id)
    else
      flash.now[:error] = "Band must have a name."
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def edit
    @band = Band.find_by(id: params[:id])
    if @band
      render :edit
    else
      flash[:error] = "Sorry, band not found."
      redirect_to bands_url
    end
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band
      render :show
    else
      flash[:error] = "Sorry, band not found."
      redirect_to bands_url
    end
  end

  def update
    @band = Band.find_by(id: params[:id])

    if @band.update(band_params)
      flash[:success] = "Band successfully edited!"
      redirect_to band_url(@band.id)
    else
      flash.now[:error] = "Band must have a name."
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @band = Band.find_by(id: params[:id])
    if @band
      flash[:success] = "Band successfully removed!"
      @band.destroy
      redirect_to bands_url
    else
      flash[:error] = "Sorry, that band was not found."
      redirect_to bands_url
    end

  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

W10D1/music_app_specs_exercise/app/views/bands/_form.html.erb
<% if band.persisted? %>
  <% action_url = band_url(band.id) %>
  <% button_text = "Change band's name" %>
  <% hidden_method = "PATCH" %>
<% else %>
  <% action_url = bands_url %>
  <% button_text = "Add band" %>
  <% hidden_method = "POST" %>
<% end %>

<form action="<%= action_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= hidden_method %>">
  <label for="band_name">Name:</label>
  <input type="text" name="band[name]" value="<%= band.name %>" id="band_name">
  <button><%= button_text %></button>
</form>

W10D1/music_app_specs_exercise/app/views/bands/edit.html.erb
<h1>Edit band!</h1>
<%= render partial: 'form', locals: { band: @band } %>

W10D1/music_app_specs_exercise/app/views/bands/index.html.erb
<h1>The Bands!</h1>
<ol>
  <% @bands.each do |band| %>
  <li><%= link_to "#{band.name}", band_url(band.id) %></li>
  <% end %>
</ol>
<%= button_to "Add a band!", new_band_url, method: :get %>

W10D1/music_app_specs_exercise/app/views/bands/new.html.erb
<h1>Add a band!</h1>
<%= render partial: 'form', locals: { band: @band } %>

W10D1/music_app_specs_exercise/app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h3>Albums:</h3>
<ol>
  <% @band.albums.each do |album| %>
  <li><%= link_to "#{album.title}", album_url(album.id) %></li>
  <% end %>
</ol>
<%= button_to "Add an album!", new_band_album_url(@band.id), method: :get %>
<%= button_to "Change band's name", edit_band_url(@band.id), method: :get %>
<%= button_to "Remove band", band_url(@band.id), method: :delete %>